2017-07-30 20:33:54.073 [error] <0.3821.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.3826.0> exit with reason normal in context child_terminated
2017-07-30 20:33:54.099 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-30 20:33:54.102 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-30 20:33:54.102 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-30 20:33:54.105 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-30 20:33:54.105 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-30 20:33:54.114 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-30 20:33:54.115 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-30 20:33:54.119 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-30 20:33:54.119 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-30 20:33:54.121 [info] <0.33.0> Application poison started on node nonode@nohost
2017-07-30 20:33:54.127 [info] <0.33.0> Application unicode_util_compat started on node nonode@nohost
2017-07-30 20:33:54.127 [info] <0.33.0> Application idna started on node nonode@nohost
2017-07-30 20:33:54.128 [info] <0.33.0> Application mimerl started on node nonode@nohost
2017-07-30 20:33:54.130 [info] <0.33.0> Application certifi started on node nonode@nohost
2017-07-30 20:33:54.131 [info] <0.33.0> Application ssl_verify_fun started on node nonode@nohost
2017-07-30 20:33:54.133 [info] <0.33.0> Application metrics started on node nonode@nohost
2017-07-30 20:33:54.146 [info] <0.33.0> Application hackney started on node nonode@nohost
2017-07-30 20:33:54.146 [info] <0.33.0> Application httpoison started on node nonode@nohost
2017-07-30 20:33:54.147 [info] <0.33.0> Application uuid started on node nonode@nohost
2017-07-30 20:33:54.149 [info] <0.33.0> Application mime started on node nonode@nohost
2017-07-30 20:33:54.149 [info] <0.33.0> Application plug started on node nonode@nohost
2017-07-30 20:35:26.621 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 20:35:26.644 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-30 20:35:26.647 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-30 20:35:26.647 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-30 20:35:26.650 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-30 20:35:26.650 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-30 20:35:26.656 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-30 20:35:26.658 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-30 20:35:26.662 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-30 20:35:26.662 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-30 20:35:26.664 [info] <0.33.0> Application poison started on node nonode@nohost
2017-07-30 20:35:26.670 [info] <0.33.0> Application unicode_util_compat started on node nonode@nohost
2017-07-30 20:35:26.670 [info] <0.33.0> Application idna started on node nonode@nohost
2017-07-30 20:35:26.672 [info] <0.33.0> Application mimerl started on node nonode@nohost
2017-07-30 20:35:26.673 [info] <0.33.0> Application certifi started on node nonode@nohost
2017-07-30 20:35:26.675 [info] <0.33.0> Application ssl_verify_fun started on node nonode@nohost
2017-07-30 20:35:26.676 [info] <0.33.0> Application metrics started on node nonode@nohost
2017-07-30 20:35:26.683 [info] <0.33.0> Application hackney started on node nonode@nohost
2017-07-30 20:35:26.683 [info] <0.33.0> Application httpoison started on node nonode@nohost
2017-07-30 20:35:26.684 [info] <0.33.0> Application uuid started on node nonode@nohost
2017-07-30 20:35:26.686 [info] <0.33.0> Application mime started on node nonode@nohost
2017-07-30 20:35:26.689 [info] <0.33.0> Application plug started on node nonode@nohost
2017-07-30 20:37:05.947 [error] <0.203.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.208.0> exit with reason normal in context child_terminated
2017-07-30 20:37:05.966 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-30 20:37:05.970 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-30 20:37:05.970 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-30 20:37:05.972 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-30 20:37:05.972 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-30 20:37:05.978 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-30 20:37:05.980 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-30 20:37:05.983 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-30 20:37:05.983 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-30 20:37:05.985 [info] <0.33.0> Application poison started on node nonode@nohost
2017-07-30 20:37:05.991 [info] <0.33.0> Application unicode_util_compat started on node nonode@nohost
2017-07-30 20:37:05.991 [info] <0.33.0> Application idna started on node nonode@nohost
2017-07-30 20:37:05.993 [info] <0.33.0> Application mimerl started on node nonode@nohost
2017-07-30 20:37:05.994 [info] <0.33.0> Application certifi started on node nonode@nohost
2017-07-30 20:37:05.996 [info] <0.33.0> Application ssl_verify_fun started on node nonode@nohost
2017-07-30 20:37:05.998 [info] <0.33.0> Application metrics started on node nonode@nohost
2017-07-30 20:37:06.005 [info] <0.33.0> Application hackney started on node nonode@nohost
2017-07-30 20:37:06.005 [info] <0.33.0> Application httpoison started on node nonode@nohost
2017-07-30 20:37:06.006 [info] <0.33.0> Application uuid started on node nonode@nohost
2017-07-30 20:37:06.008 [info] <0.33.0> Application mime started on node nonode@nohost
2017-07-30 20:37:06.011 [info] <0.33.0> Application plug started on node nonode@nohost
2017-07-30 20:37:11.236 [info] <0.425.0>@h2_connection:route_frame:545 [client] Stream 1 WindowUpdate 9
2017-07-30 20:44:35.808 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 20:44:35.831 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-30 20:44:35.835 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-30 20:44:35.835 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-30 20:44:35.838 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-30 20:44:35.838 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-30 20:44:35.844 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-30 20:44:35.846 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-30 20:44:35.850 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-30 20:44:35.850 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-30 20:44:35.852 [info] <0.33.0> Application poison started on node nonode@nohost
2017-07-30 20:44:35.858 [info] <0.33.0> Application unicode_util_compat started on node nonode@nohost
2017-07-30 20:44:35.858 [info] <0.33.0> Application idna started on node nonode@nohost
2017-07-30 20:44:35.860 [info] <0.33.0> Application mimerl started on node nonode@nohost
2017-07-30 20:44:35.861 [info] <0.33.0> Application certifi started on node nonode@nohost
2017-07-30 20:44:35.863 [info] <0.33.0> Application ssl_verify_fun started on node nonode@nohost
2017-07-30 20:44:35.865 [info] <0.33.0> Application metrics started on node nonode@nohost
2017-07-30 20:44:35.872 [info] <0.33.0> Application hackney started on node nonode@nohost
2017-07-30 20:44:35.872 [info] <0.33.0> Application httpoison started on node nonode@nohost
2017-07-30 20:44:35.873 [info] <0.33.0> Application uuid started on node nonode@nohost
2017-07-30 20:44:35.875 [info] <0.33.0> Application mime started on node nonode@nohost
2017-07-30 20:44:35.880 [info] <0.33.0> Application plug started on node nonode@nohost
2017-07-30 20:44:40.578 [info] <0.414.0>@h2_connection:route_frame:545 [client] Stream 1 WindowUpdate 7
2017-07-30 20:45:10.243 [info] <0.414.0>@h2_connection:route_frame:545 [client] Stream 3 WindowUpdate 7
2017-07-30 20:45:13.249 [info] <0.414.0>@h2_connection:route_frame:545 [client] Stream 5 WindowUpdate 7
2017-07-30 20:45:16.681 [info] <0.414.0>@h2_connection:route_frame:545 [client] Stream 7 WindowUpdate 7
2017-07-30 22:48:36.154 [error] <0.3825.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.3830.0> exit with reason normal in context child_terminated
2017-07-30 22:48:36.178 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-30 22:48:36.182 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-30 22:48:36.182 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-30 22:48:36.184 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-30 22:48:36.184 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-30 22:48:36.194 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-30 22:48:36.195 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-30 22:48:36.199 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-30 22:48:36.199 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-30 22:48:36.201 [info] <0.33.0> Application poison started on node nonode@nohost
2017-07-30 22:48:36.206 [info] <0.33.0> Application unicode_util_compat started on node nonode@nohost
2017-07-30 22:48:36.206 [info] <0.33.0> Application idna started on node nonode@nohost
2017-07-30 22:48:36.208 [info] <0.33.0> Application mimerl started on node nonode@nohost
2017-07-30 22:48:36.209 [info] <0.33.0> Application certifi started on node nonode@nohost
2017-07-30 22:48:36.211 [info] <0.33.0> Application ssl_verify_fun started on node nonode@nohost
2017-07-30 22:48:36.212 [info] <0.33.0> Application metrics started on node nonode@nohost
2017-07-30 22:48:36.226 [info] <0.33.0> Application hackney started on node nonode@nohost
2017-07-30 22:48:36.226 [info] <0.33.0> Application httpoison started on node nonode@nohost
2017-07-30 22:48:36.227 [info] <0.33.0> Application uuid started on node nonode@nohost
2017-07-30 22:48:36.229 [info] <0.33.0> Application mime started on node nonode@nohost
2017-07-30 22:48:36.230 [info] <0.33.0> Application plug started on node nonode@nohost
2017-07-30 22:48:36.264 [error] <0.3928.0> gen_server <0.3928.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:36.265 [error] <0.3928.0> CRASH REPORT Process <0.3928.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:36.266 [error] <0.4301.0> gen_server <0.4301.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:36.266 [error] <0.4301.0> CRASH REPORT Process <0.4301.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:36.266 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.4301.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:36.266 [error] <0.4302.0> gen_server <0.4302.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:36.267 [error] <0.4302.0> CRASH REPORT Process <0.4302.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:36.267 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.4302.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:36.267 [error] <0.4303.0> gen_server <0.4303.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:36.267 [error] <0.4303.0> CRASH REPORT Process <0.4303.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:36.267 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.4303.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:36.268 [error] <0.4304.0> gen_server <0.4304.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:36.268 [error] <0.4304.0> CRASH REPORT Process <0.4304.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:36.268 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.4304.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:36.269 [error] <0.4305.0> gen_server <0.4305.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:36.269 [error] <0.4305.0> CRASH REPORT Process <0.4305.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:36.269 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.4305.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.000 [warning] <0.32.0> lager_error_logger_h dropped 38940 messages in the last second that exceeded the limit of 50 messages/sec
2017-07-30 22:48:37.000 [error] <0.18255.0> gen_server <0.18255.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.001 [error] <0.18255.0> CRASH REPORT Process <0.18255.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.001 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18255.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.002 [error] <0.18256.0> gen_server <0.18256.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.003 [error] <0.18256.0> CRASH REPORT Process <0.18256.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.003 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18256.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.004 [error] <0.18257.0> gen_server <0.18257.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.004 [error] <0.18257.0> CRASH REPORT Process <0.18257.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.005 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18257.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.005 [error] <0.18258.0> gen_server <0.18258.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.006 [error] <0.18258.0> CRASH REPORT Process <0.18258.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.006 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18258.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.006 [error] <0.18259.0> gen_server <0.18259.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.006 [error] <0.18259.0> CRASH REPORT Process <0.18259.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.007 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18259.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.007 [error] <0.18260.0> gen_server <0.18260.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.007 [error] <0.18260.0> CRASH REPORT Process <0.18260.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.007 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18260.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.008 [error] <0.18261.0> gen_server <0.18261.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.008 [error] <0.18261.0> CRASH REPORT Process <0.18261.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.008 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18261.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.009 [error] <0.18262.0> gen_server <0.18262.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.009 [error] <0.18262.0> CRASH REPORT Process <0.18262.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.009 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18262.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.009 [error] <0.18263.0> gen_server <0.18263.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.010 [error] <0.18263.0> CRASH REPORT Process <0.18263.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.010 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18263.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.010 [error] <0.18264.0> gen_server <0.18264.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.010 [error] <0.18264.0> CRASH REPORT Process <0.18264.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.011 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18264.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.011 [error] <0.18265.0> gen_server <0.18265.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.022 [error] <0.18265.0> CRASH REPORT Process <0.18265.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.022 [error] <0.18643.0> CRASH REPORT Process <0.18643.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.022 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18643.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.022 [error] <0.18644.0> gen_server <0.18644.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.022 [error] <0.18644.0> CRASH REPORT Process <0.18644.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.023 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18644.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.023 [error] <0.18645.0> gen_server <0.18645.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.023 [error] <0.18645.0> CRASH REPORT Process <0.18645.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.023 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18645.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.024 [error] <0.18646.0> gen_server <0.18646.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.024 [error] <0.18646.0> CRASH REPORT Process <0.18646.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.024 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18646.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.025 [error] <0.18647.0> gen_server <0.18647.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.025 [error] <0.18647.0> CRASH REPORT Process <0.18647.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.025 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18647.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.026 [error] <0.18648.0> gen_server <0.18648.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:37.026 [error] <0.18648.0> CRASH REPORT Process <0.18648.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:37.026 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.18648.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:37.026 [error] <0.18649.0> gen_server <0.18649.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.000 [warning] <0.32.0> lager_error_logger_h dropped 53858 messages in the last second that exceeded the limit of 50 messages/sec
2017-07-30 22:48:38.000 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5077.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.000 [error] <0.5078.1> gen_server <0.5078.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.000 [error] <0.5078.1> CRASH REPORT Process <0.5078.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.001 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5078.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.001 [error] <0.5079.1> gen_server <0.5079.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.001 [error] <0.5079.1> CRASH REPORT Process <0.5079.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.001 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5079.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.002 [error] <0.5080.1> gen_server <0.5080.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.002 [error] <0.5080.1> CRASH REPORT Process <0.5080.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.002 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5080.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.003 [error] <0.5081.1> gen_server <0.5081.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.003 [error] <0.5081.1> CRASH REPORT Process <0.5081.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.003 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5081.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.003 [error] <0.5082.1> gen_server <0.5082.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.003 [error] <0.5082.1> CRASH REPORT Process <0.5082.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.004 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5082.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.004 [error] <0.5083.1> gen_server <0.5083.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.004 [error] <0.5083.1> CRASH REPORT Process <0.5083.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.004 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5083.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.005 [error] <0.5084.1> gen_server <0.5084.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.005 [error] <0.5084.1> CRASH REPORT Process <0.5084.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.005 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5084.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.005 [error] <0.5085.1> gen_server <0.5085.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.006 [error] <0.5085.1> CRASH REPORT Process <0.5085.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.006 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5085.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.006 [error] <0.5086.1> gen_server <0.5086.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.006 [error] <0.5086.1> CRASH REPORT Process <0.5086.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.006 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5086.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.007 [error] <0.5087.1> gen_server <0.5087.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.018 [error] <0.5087.1> CRASH REPORT Process <0.5087.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.018 [error] <0.5406.1> gen_server <0.5406.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.018 [error] <0.5406.1> CRASH REPORT Process <0.5406.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.019 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5406.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.019 [error] <0.5407.1> gen_server <0.5407.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.019 [error] <0.5407.1> CRASH REPORT Process <0.5407.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.019 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5407.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.020 [error] <0.5408.1> gen_server <0.5408.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.020 [error] <0.5408.1> CRASH REPORT Process <0.5408.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.020 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5408.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.021 [error] <0.5409.1> gen_server <0.5409.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.021 [error] <0.5409.1> CRASH REPORT Process <0.5409.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.021 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5409.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.021 [error] <0.5410.1> gen_server <0.5410.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.021 [error] <0.5410.1> CRASH REPORT Process <0.5410.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.022 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5410.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.022 [error] <0.5411.1> gen_server <0.5411.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.022 [error] <0.5411.1> CRASH REPORT Process <0.5411.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:38.022 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.5411.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:38.023 [error] <0.5412.1> gen_server <0.5412.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:38.023 [error] <0.5412.1> CRASH REPORT Process <0.5412.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.000 [warning] <0.32.0> lager_error_logger_h dropped 52359 messages in the last second that exceeded the limit of 50 messages/sec
2017-07-30 22:48:39.000 [error] <0.24085.1> gen_server <0.24085.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.000 [error] <0.24085.1> CRASH REPORT Process <0.24085.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.001 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24085.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.001 [error] <0.24086.1> gen_server <0.24086.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.001 [error] <0.24086.1> CRASH REPORT Process <0.24086.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.002 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24086.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.002 [error] <0.24087.1> gen_server <0.24087.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.002 [error] <0.24087.1> CRASH REPORT Process <0.24087.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.002 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24087.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.003 [error] <0.24088.1> gen_server <0.24088.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.003 [error] <0.24088.1> CRASH REPORT Process <0.24088.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.003 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24088.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.004 [error] <0.24089.1> gen_server <0.24089.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.004 [error] <0.24089.1> CRASH REPORT Process <0.24089.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.004 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24089.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.005 [error] <0.24090.1> gen_server <0.24090.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.005 [error] <0.24090.1> CRASH REPORT Process <0.24090.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.005 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24090.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.005 [error] <0.24091.1> gen_server <0.24091.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.005 [error] <0.24091.1> CRASH REPORT Process <0.24091.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.006 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24091.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.006 [error] <0.24092.1> gen_server <0.24092.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.006 [error] <0.24092.1> CRASH REPORT Process <0.24092.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.006 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24092.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.008 [error] <0.24093.1> gen_server <0.24093.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.008 [error] <0.24093.1> CRASH REPORT Process <0.24093.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.008 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24093.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.009 [error] <0.24094.1> gen_server <0.24094.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.019 [error] <0.24094.1> CRASH REPORT Process <0.24094.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.020 [error] <0.24360.1> gen_server <0.24360.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.020 [error] <0.24360.1> CRASH REPORT Process <0.24360.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.020 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24360.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.020 [error] <0.24361.1> gen_server <0.24361.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.020 [error] <0.24361.1> CRASH REPORT Process <0.24361.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.021 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24361.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.021 [error] <0.24362.1> gen_server <0.24362.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.021 [error] <0.24362.1> CRASH REPORT Process <0.24362.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.021 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24362.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.022 [error] <0.24363.1> gen_server <0.24363.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.022 [error] <0.24363.1> CRASH REPORT Process <0.24363.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.022 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24363.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.023 [error] <0.24364.1> gen_server <0.24364.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.023 [error] <0.24364.1> CRASH REPORT Process <0.24364.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.023 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24364.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.023 [error] <0.24365.1> gen_server <0.24365.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.024 [error] <0.24365.1> CRASH REPORT Process <0.24365.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.024 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24365.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:39.024 [error] <0.24366.1> gen_server <0.24366.1> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:39.024 [error] <0.24366.1> CRASH REPORT Process <0.24366.1> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:39.025 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.24366.1> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.000 [warning] <0.32.0> lager_error_logger_h dropped 52718 messages in the last second that exceeded the limit of 50 messages/sec
2017-07-30 22:48:40.000 [error] <0.10406.2> gen_server <0.10406.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.000 [error] <0.10406.2> CRASH REPORT Process <0.10406.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.000 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10406.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.001 [error] <0.10407.2> gen_server <0.10407.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.001 [error] <0.10407.2> CRASH REPORT Process <0.10407.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.001 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10407.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.002 [error] <0.10408.2> gen_server <0.10408.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.002 [error] <0.10408.2> CRASH REPORT Process <0.10408.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.002 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10408.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.002 [error] <0.10409.2> gen_server <0.10409.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.002 [error] <0.10409.2> CRASH REPORT Process <0.10409.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.003 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10409.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.003 [error] <0.10410.2> gen_server <0.10410.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.003 [error] <0.10410.2> CRASH REPORT Process <0.10410.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.003 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10410.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.004 [error] <0.10411.2> gen_server <0.10411.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.004 [error] <0.10411.2> CRASH REPORT Process <0.10411.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.004 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10411.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.005 [error] <0.10412.2> gen_server <0.10412.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.005 [error] <0.10412.2> CRASH REPORT Process <0.10412.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.005 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10412.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.005 [error] <0.10413.2> gen_server <0.10413.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.005 [error] <0.10413.2> CRASH REPORT Process <0.10413.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.006 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10413.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.006 [error] <0.10414.2> gen_server <0.10414.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.006 [error] <0.10414.2> CRASH REPORT Process <0.10414.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.006 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10414.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.007 [error] <0.10415.2> gen_server <0.10415.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.007 [error] <0.10415.2> CRASH REPORT Process <0.10415.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.007 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10415.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.008 [error] <0.10416.2> gen_server <0.10416.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.008 [error] <0.10416.2> CRASH REPORT Process <0.10416.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.008 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10416.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.008 [error] <0.10417.2> gen_server <0.10417.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.019 [error] <0.10417.2> CRASH REPORT Process <0.10417.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.020 [error] <0.10809.2> gen_server <0.10809.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.020 [error] <0.10809.2> CRASH REPORT Process <0.10809.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.021 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10809.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.021 [error] <0.10810.2> gen_server <0.10810.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.021 [error] <0.10810.2> CRASH REPORT Process <0.10810.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.021 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10810.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.022 [error] <0.10811.2> gen_server <0.10811.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.022 [error] <0.10811.2> CRASH REPORT Process <0.10811.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.022 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10811.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.023 [error] <0.10812.2> gen_server <0.10812.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.023 [error] <0.10812.2> CRASH REPORT Process <0.10812.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.023 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10812.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 22:48:40.023 [error] <0.10813.2> gen_server <0.10813.2> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371
2017-07-30 22:48:40.023 [error] <0.10813.2> CRASH REPORT Process <0.10813.2> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in 'Elixir.Connection':enter_stop/5 line 686
2017-07-30 22:48:40.024 [error] <0.3927.0> Supervisor {<0.3927.0>,poolboy_sup} had child 'Elixir.DBConnection.Poolboy.Worker' started with {'Elixir.DBConnection.Poolboy.Worker',start_link,undefined} at <0.10813.2> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.KeyError',key => database,term => [{hostname,<<"localhost">>},{username,<<"nemanja">>},{types,'Elixir.Ecto.Adapters.Postgres.TypeModule'},{port,5432},{name,'Elixir.UsvcOtisak.Repo.Pool'},{otp_app,usvc_otisak},{repo,'Elixir.UsvcOtisak.Repo'},{adapter,'Elixir.Ecto.Adapters.Postgres'},{pool_timeout,5000},{timeout,15000},{adapter,'Elixir.Ecto.Adapters.Postgres'},{url,{system,<<"DB_URL">>}},{pool,'Elixir.DBConnection.Poolboy'}]} in 'Elixir.Keyword':'fetch!'/2 line 371 in context child_terminated
2017-07-30 20:50:10.599 [error] <0.3823.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.3828.0> exit with reason normal in context child_terminated
2017-07-30 20:50:10.628 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-30 20:50:10.631 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-30 20:50:10.631 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-30 20:50:10.633 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-30 20:50:10.633 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-30 20:50:10.644 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-30 20:50:10.645 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-30 20:50:10.649 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-30 20:50:10.649 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-30 20:50:10.651 [info] <0.33.0> Application poison started on node nonode@nohost
2017-07-30 20:50:10.656 [info] <0.33.0> Application unicode_util_compat started on node nonode@nohost
2017-07-30 20:50:10.656 [info] <0.33.0> Application idna started on node nonode@nohost
2017-07-30 20:50:10.658 [info] <0.33.0> Application mimerl started on node nonode@nohost
2017-07-30 20:50:10.660 [info] <0.33.0> Application certifi started on node nonode@nohost
2017-07-30 20:50:10.661 [info] <0.33.0> Application ssl_verify_fun started on node nonode@nohost
2017-07-30 20:50:10.663 [info] <0.33.0> Application metrics started on node nonode@nohost
2017-07-30 20:50:10.677 [info] <0.33.0> Application hackney started on node nonode@nohost
2017-07-30 20:50:10.677 [info] <0.33.0> Application httpoison started on node nonode@nohost
2017-07-30 20:50:10.678 [info] <0.33.0> Application uuid started on node nonode@nohost
2017-07-30 20:50:10.680 [info] <0.33.0> Application mime started on node nonode@nohost
2017-07-30 20:50:10.680 [info] <0.33.0> Application plug started on node nonode@nohost
2017-07-30 20:50:10.732 [error] <0.3942.0> Failed to start Ranch listener 'Elixir.UsvcOtisak.Router.HTTP' in ranch_tcp:listen([{port,4000}]) for reason eaddrinuse (address already in use)
2017-07-30 20:50:10.732 [error] <0.3942.0> CRASH REPORT Process <0.3942.0> with 0 neighbours exited with reason: {listen_error,'Elixir.UsvcOtisak.Router.HTTP',eaddrinuse} in gen_server:init_it/6 line 352
2017-07-30 20:50:10.732 [error] <0.3936.0> Supervisor {<0.3936.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.UsvcOtisak.Router.HTTP', 100, ranch_tcp, [{max_connections,16384},{port,4000}]) at undefined exit with reason {listen_error,'Elixir.UsvcOtisak.Router.HTTP',eaddrinuse} in context start_error
2017-07-30 20:50:10.732 [error] <0.3922.0> Supervisor 'Elixir.Ppp.Supervisor' had child {ranch_listener_sup,'Elixir.UsvcOtisak.Router.HTTP'} started with ranch_listener_sup:start_link('Elixir.UsvcOtisak.Router.HTTP', 100, ranch_tcp, [{max_connections,16384},{port,4000}], cowboy_protocol, [{env,[{dispatch,[{'_',[],[{'_',[],'Elixir.Plug.Adapters.Cowboy.Handler',{'Elixir.UsvcOtisak.Router',...}}]}]}]}]) at undefined exit with reason {shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.UsvcOtisak.Router.HTTP',eaddrinuse}}} in context start_error
2017-07-30 20:50:10.732 [error] <0.3920.0> CRASH REPORT Process <0.3920.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.UsvcOtisak.Router.HTTP'},{shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.UsvcOtisak.Router.HTTP',eaddrinuse}}}}},{'Elixir.UsvcOtisak.Application',start,[normal,[]]}} in application_master:init/4 line 134
2017-07-30 20:50:10.732 [info] <0.33.0> Application usvc_otisak exited with reason: {{shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.UsvcOtisak.Router.HTTP'},{shutdown,{failed_to_start_child,ranch_acceptors_sup,{listen_error,'Elixir.UsvcOtisak.Router.HTTP',eaddrinuse}}}}},{'Elixir.UsvcOtisak.Application',start,[normal,[]]}}
2017-07-30 20:50:10.733 [info] <0.33.0> Application plug exited with reason: stopped
2017-07-30 20:50:10.733 [info] <0.33.0> Application mime exited with reason: stopped
2017-07-30 20:50:10.733 [info] <0.33.0> Application uuid exited with reason: stopped
2017-07-30 20:50:10.733 [info] <0.33.0> Application httpoison exited with reason: stopped
2017-07-30 20:50:10.733 [info] <0.33.0> Application hackney exited with reason: stopped
2017-07-30 20:50:10.733 [info] <0.33.0> Application metrics exited with reason: stopped
2017-07-30 20:50:10.733 [info] <0.33.0> Application ssl_verify_fun exited with reason: stopped
2017-07-30 20:52:48.907 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 20:52:48.932 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-30 20:52:48.936 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-30 20:52:48.936 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-30 20:52:48.939 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-30 20:52:48.939 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-30 20:52:48.946 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-30 20:52:48.948 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-30 20:52:48.950 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-30 20:52:48.950 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-30 20:52:48.952 [info] <0.33.0> Application poison started on node nonode@nohost
2017-07-30 20:52:48.959 [info] <0.33.0> Application unicode_util_compat started on node nonode@nohost
2017-07-30 20:52:48.959 [info] <0.33.0> Application idna started on node nonode@nohost
2017-07-30 20:52:48.961 [info] <0.33.0> Application mimerl started on node nonode@nohost
2017-07-30 20:52:48.962 [info] <0.33.0> Application certifi started on node nonode@nohost
2017-07-30 20:52:48.964 [info] <0.33.0> Application ssl_verify_fun started on node nonode@nohost
2017-07-30 20:52:48.966 [info] <0.33.0> Application metrics started on node nonode@nohost
2017-07-30 20:52:48.973 [info] <0.33.0> Application hackney started on node nonode@nohost
2017-07-30 20:52:48.973 [info] <0.33.0> Application httpoison started on node nonode@nohost
2017-07-30 20:52:48.975 [info] <0.33.0> Application uuid started on node nonode@nohost
2017-07-30 20:52:48.977 [info] <0.33.0> Application mime started on node nonode@nohost
2017-07-30 20:52:48.981 [info] <0.33.0> Application plug started on node nonode@nohost
2017-07-30 20:53:48.937 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 20:53:48.962 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-30 20:53:48.966 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-30 20:53:48.966 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-30 20:53:48.968 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-30 20:53:48.968 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-30 20:53:48.974 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-30 20:53:48.975 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-30 20:53:48.979 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-30 20:53:48.979 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-30 20:53:48.981 [info] <0.33.0> Application poison started on node nonode@nohost
2017-07-30 20:53:48.987 [info] <0.33.0> Application unicode_util_compat started on node nonode@nohost
2017-07-30 20:53:48.987 [info] <0.33.0> Application idna started on node nonode@nohost
2017-07-30 20:53:48.988 [info] <0.33.0> Application mimerl started on node nonode@nohost
2017-07-30 20:53:48.990 [info] <0.33.0> Application certifi started on node nonode@nohost
2017-07-30 20:53:48.991 [info] <0.33.0> Application ssl_verify_fun started on node nonode@nohost
2017-07-30 20:53:48.993 [info] <0.33.0> Application metrics started on node nonode@nohost
2017-07-30 20:53:49.000 [info] <0.33.0> Application hackney started on node nonode@nohost
2017-07-30 20:53:49.000 [info] <0.33.0> Application httpoison started on node nonode@nohost
2017-07-30 20:53:49.001 [info] <0.33.0> Application uuid started on node nonode@nohost
2017-07-30 20:53:49.002 [info] <0.33.0> Application mime started on node nonode@nohost
2017-07-30 20:53:49.005 [info] <0.33.0> Application plug started on node nonode@nohost
2017-07-30 20:54:47.370 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 20:54:47.393 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-30 20:54:47.396 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-30 20:54:47.397 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-30 20:54:47.399 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-30 20:54:47.399 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-30 20:54:47.406 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-30 20:54:47.407 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-30 20:54:47.411 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-30 20:54:47.411 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-30 20:54:47.414 [info] <0.33.0> Application poison started on node nonode@nohost
2017-07-30 20:54:47.421 [info] <0.33.0> Application unicode_util_compat started on node nonode@nohost
2017-07-30 20:54:47.421 [info] <0.33.0> Application idna started on node nonode@nohost
2017-07-30 20:54:47.423 [info] <0.33.0> Application mimerl started on node nonode@nohost
2017-07-30 20:54:47.424 [info] <0.33.0> Application certifi started on node nonode@nohost
2017-07-30 20:54:47.426 [info] <0.33.0> Application ssl_verify_fun started on node nonode@nohost
2017-07-30 20:54:47.428 [info] <0.33.0> Application metrics started on node nonode@nohost
2017-07-30 20:54:47.436 [info] <0.33.0> Application hackney started on node nonode@nohost
2017-07-30 20:54:47.436 [info] <0.33.0> Application httpoison started on node nonode@nohost
2017-07-30 20:54:47.437 [info] <0.33.0> Application uuid started on node nonode@nohost
2017-07-30 20:54:47.439 [info] <0.33.0> Application mime started on node nonode@nohost
2017-07-30 20:54:47.443 [info] <0.33.0> Application plug started on node nonode@nohost
2017-07-30 20:58:34.133 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 20:58:34.152 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-30 20:58:34.155 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-30 20:58:34.156 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-30 20:58:34.158 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-30 20:58:34.158 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-30 20:58:34.165 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-30 20:58:34.166 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-30 20:58:34.171 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-30 20:58:34.171 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-30 20:58:34.172 [info] <0.33.0> Application poison started on node nonode@nohost
2017-07-30 20:58:34.179 [info] <0.33.0> Application unicode_util_compat started on node nonode@nohost
2017-07-30 20:58:34.179 [info] <0.33.0> Application idna started on node nonode@nohost
2017-07-30 20:58:34.181 [info] <0.33.0> Application mimerl started on node nonode@nohost
2017-07-30 20:58:34.182 [info] <0.33.0> Application certifi started on node nonode@nohost
2017-07-30 20:58:34.184 [info] <0.33.0> Application ssl_verify_fun started on node nonode@nohost
2017-07-30 20:58:34.185 [info] <0.33.0> Application metrics started on node nonode@nohost
2017-07-30 20:58:34.195 [info] <0.33.0> Application hackney started on node nonode@nohost
2017-07-30 20:58:34.195 [info] <0.33.0> Application httpoison started on node nonode@nohost
2017-07-30 20:58:34.197 [info] <0.33.0> Application uuid started on node nonode@nohost
2017-07-30 20:58:34.199 [info] <0.33.0> Application mime started on node nonode@nohost
2017-07-30 20:58:34.204 [info] <0.33.0> Application plug started on node nonode@nohost
2017-07-30 20:58:46.755 [info] <0.414.0>@h2_connection:route_frame:545 [client] Stream 1 WindowUpdate 7
2017-07-30 21:00:03.578 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 21:00:03.603 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-30 21:00:03.606 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-30 21:00:03.606 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-30 21:00:03.609 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-30 21:00:03.609 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-30 21:00:03.617 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-30 21:00:03.620 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-30 21:00:03.622 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-30 21:00:03.622 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-30 21:00:03.624 [info] <0.33.0> Application poison started on node nonode@nohost
2017-07-30 21:00:03.631 [info] <0.33.0> Application unicode_util_compat started on node nonode@nohost
2017-07-30 21:00:03.631 [info] <0.33.0> Application idna started on node nonode@nohost
2017-07-30 21:00:03.633 [info] <0.33.0> Application mimerl started on node nonode@nohost
2017-07-30 21:00:03.634 [info] <0.33.0> Application certifi started on node nonode@nohost
2017-07-30 21:00:03.636 [info] <0.33.0> Application ssl_verify_fun started on node nonode@nohost
2017-07-30 21:00:03.638 [info] <0.33.0> Application metrics started on node nonode@nohost
2017-07-30 21:00:03.646 [info] <0.33.0> Application hackney started on node nonode@nohost
2017-07-30 21:00:03.646 [info] <0.33.0> Application httpoison started on node nonode@nohost
2017-07-30 21:00:03.648 [info] <0.33.0> Application uuid started on node nonode@nohost
2017-07-30 21:00:03.651 [info] <0.33.0> Application mime started on node nonode@nohost
2017-07-30 21:00:03.654 [info] <0.33.0> Application plug started on node nonode@nohost
2017-07-30 21:00:09.843 [info] <0.414.0>@h2_connection:route_frame:545 [client] Stream 1 WindowUpdate 7
2017-07-30 21:02:39.162 [error] <0.3092.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.3097.0> exit with reason normal in context child_terminated
2017-07-30 21:02:39.206 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-30 21:02:39.211 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-30 21:02:39.211 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-30 21:02:39.214 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-30 21:02:39.214 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-30 21:02:39.229 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-30 21:02:39.230 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-30 21:02:39.242 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-30 21:02:39.242 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-30 21:02:39.244 [info] <0.33.0> Application poison started on node nonode@nohost
2017-07-30 21:02:39.251 [info] <0.33.0> Application unicode_util_compat started on node nonode@nohost
2017-07-30 21:02:39.252 [info] <0.33.0> Application idna started on node nonode@nohost
2017-07-30 21:02:39.256 [info] <0.33.0> Application mimerl started on node nonode@nohost
2017-07-30 21:02:39.258 [info] <0.33.0> Application certifi started on node nonode@nohost
2017-07-30 21:02:39.259 [info] <0.33.0> Application ssl_verify_fun started on node nonode@nohost
2017-07-30 21:02:39.261 [info] <0.33.0> Application metrics started on node nonode@nohost
2017-07-30 21:02:39.280 [info] <0.33.0> Application hackney started on node nonode@nohost
2017-07-30 21:02:39.280 [info] <0.33.0> Application httpoison started on node nonode@nohost
2017-07-30 21:02:39.281 [info] <0.33.0> Application uuid started on node nonode@nohost
2017-07-30 21:02:39.285 [info] <0.33.0> Application mime started on node nonode@nohost
2017-07-30 21:02:39.286 [info] <0.33.0> Application plug started on node nonode@nohost
2017-07-30 21:02:48.509 [info] <0.3314.0>@h2_connection:route_frame:545 [client] Stream 1 WindowUpdate 7
2017-07-30 21:04:19.317 [error] <0.192.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.197.0> exit with reason normal in context child_terminated
2017-07-30 21:04:19.341 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-30 21:04:19.344 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-30 21:04:19.344 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-30 21:04:19.347 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-30 21:04:19.347 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-30 21:04:19.354 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-30 21:04:19.356 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-30 21:04:19.360 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-30 21:04:19.360 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-30 21:04:19.361 [info] <0.33.0> Application poison started on node nonode@nohost
2017-07-30 21:04:19.368 [info] <0.33.0> Application unicode_util_compat started on node nonode@nohost
2017-07-30 21:04:19.368 [info] <0.33.0> Application idna started on node nonode@nohost
2017-07-30 21:04:19.370 [info] <0.33.0> Application mimerl started on node nonode@nohost
2017-07-30 21:04:19.372 [info] <0.33.0> Application certifi started on node nonode@nohost
2017-07-30 21:04:19.374 [info] <0.33.0> Application ssl_verify_fun started on node nonode@nohost
2017-07-30 21:04:19.375 [info] <0.33.0> Application metrics started on node nonode@nohost
2017-07-30 21:04:19.383 [info] <0.33.0> Application hackney started on node nonode@nohost
2017-07-30 21:04:19.383 [info] <0.33.0> Application httpoison started on node nonode@nohost
2017-07-30 21:04:19.384 [info] <0.33.0> Application uuid started on node nonode@nohost
2017-07-30 21:04:19.387 [info] <0.33.0> Application mime started on node nonode@nohost
2017-07-30 21:04:19.390 [info] <0.33.0> Application plug started on node nonode@nohost
2017-07-30 21:04:24.274 [info] <0.414.0>@h2_connection:route_frame:545 [client] Stream 1 WindowUpdate 9
2017-07-30 21:21:28.466 [info] <0.414.0>@h2_connection:route_frame:545 [client] Stream 3 WindowUpdate 9
